version: '3.8'
services:
  app:
    image: argyarijal/mqtt-client-ta:latest
    environment:
      - ORG_INFLUX=${ORG_INFLUX}
      - BUCKET_INFLUX=${BUCKET_INFLUX}
      - URL_INFLUX=${URL_INFLUX}
      - TOKEN_INFLUX=${TOKEN_INFLUX}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    networks:
      - db-network
      - service-networks
    ports:
      - "8787:8080"
    restart: unless-stopped

networks:
  db-network:
    external: true
  service-networks:
    external: true
